spring:
  application:
    name: stock-service

server:
  port: 8302

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8443/eureka/
  instance:
    hostname: localhost